FROM ubuntu:20.04

COPY RSA/pgpool/pgpool_id_rsa /root/.ssh/id_rsa
COPY RSA/pgpool/pgpool_id_rsa.pub /root/.ssh/id_rsa.pub

RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/id_rsa

RUN mkdir /var/run/sshd

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteradockective apt-get install -y pgpool2 postgresql-client openssh-server

COPY pgpool.conf /etc/pgpool2/pgpool.conf
COPY pgpool-entrypoint.sh /pgpool-entrypoint.sh

ENTRYPOINT ["/bin/bash", "/pgpool-entrypoint.sh"]