FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y pgpool2 postgresql-client 

COPY pgpool.conf /etc/pgpool2/pgpool.conf
COPY pgpool-entrypoint.sh /pgpool-entrypoint.sh

ENTRYPOINT ["/bin/bash", "/pgpool-entrypoint.sh"]