FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

COPY ./Library.Database.Migrator.Psql.csproj ./
RUN dotnet restore

COPY ./Program.cs ./Program.cs
COPY ./CustomTableJournal.cs ./CustomTableJournal.cs

RUN dotnet build -c Release -o /app/build

RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime

COPY --from=build /app/publish /migratorapp
COPY ./Scripts/Migrations /Scripts/Migrations
COPY ./Scripts/Seeds /Scripts/Seeds

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1