FROM postgres:15

COPY RSA/pgpool/pgpool_id_rsa.pub /root/.ssh/pgpool_id_rsa.pub
RUN cat /root/.ssh/pgpool_id_rsa.pub >> /root/.ssh/authorized_keys
RUN rm /root/.ssh/pgpool_id_rsa.pub
RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/authorized_keys

RUN mkdir /var/run/sshd

RUN apt-get update && \
    apt-get install -y \
    postgresql-15-repmgr \
    openssh-server