erDiagram
        
    Patron {
        id uuid PK
        patron_type string
        version_id int
    }
    
    Book {
        id uuid PK
        library_branch_id uuid
        book_category string
        version_id int
    }
    
    Hold {
        id uuid PK
        patron_id uuid FK
        book_id uuid FK
        library_branch_id uuid
        status string
        created_at date
        till date
        is_active bool
        version_id int
    }
    
    OutboxMessage {
        id uuid PK
        occurred_on date
        processed_at date
        type string
        data string
    }
    
    Hold || -- || Patron: is_placed_by
    Hold || -- || Book: is_placed_on
