version: '3'
services:
  raven-one:
    container_name: library-one
    image: ravendb/ravendb:latest
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      RAVEN_Security_UnsecuredAccessAllowed: PublicNetwork
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: true
      RAVEN_License: ${LIBRARY_RAVEN_License} 
      RAVEN_ServerUrl: http://0.0.0.0:8080
      RAVEN_ServerUrl_Tcp: tcp://0.0.0.0:38888
      RAVEN_PublicServerUrl: http://library-one:8080
      RAVEN_PublicServerUrl_Tcp: tcp://library-one:38888
    networks:
      - library
  
  raven-two:
    container_name: library-two
    image: ravendb/ravendb:latest
    ports:
      - "8081:8081"
      - "38889:38889"
    environment:
      RAVEN_Security_UnsecuredAccessAllowed: PublicNetwork
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: true
      RAVEN_ServerUrl: http://0.0.0.0:8081
      RAVEN_ServerUrl_Tcp: tcp://0.0.0.0:38889
      RAVEN_PublicServerUrl: http://library-two:8081
      RAVEN_PublicServerUrl_Tcp: tcp://library-two:38889
    networks:
      - library
  
  raven-three:
    container_name: library-three
    image: ravendb/ravendb:latest
    ports:
      - "8082:8082"
      - "38890:38890"
    environment:
      RAVEN_Security_UnsecuredAccessAllowed: PublicNetwork
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: true
      RAVEN_ServerUrl: http://0.0.0.0:8082
      RAVEN_ServerUrl_Tcp: tcp://0.0.0.0:38890
      RAVEN_PublicServerUrl: http://library-three:8082
      RAVEN_PublicServerUrl_Tcp: tcp://library-three:38890
    networks:
      - library
  
  migrator:
    container_name: migrator-raven
    build:
      context: ../../.
      dockerfile: Dockerfile-Migrator-Raven
    networks:
      - library
    depends_on:
      raven-one:
        condition: service_started
      raven-two:
        condition: service_started
      raven-three:
        condition: service_started
    
networks:
  library:
    driver: bridge
   