name: ci-pipeline

on:
  push:
    branches:
      - master

jobs:
  reservation-module-unit-tests:
    name: reservation module unit tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      test-project: ./Library.Modules.Reservation.Domain.UnitTests

  reservation-module-integration-tests:
    name: reservation module integration tests
    needs: reservation-module-unit-tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      test-project: ./Library.Modules.Reservation.IntegrationTests

  reservation-module-architecture-tests:
    name: reservation module architecture tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      test-project: ./Library.Modules.Reservation.ArchTests

  catalogue-module-integration-tests:
    name: catalogue module integration tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      test-project: ./Library.Modules.Catalogue.IntegrationTests
  
  catalogue-module-architecture-tests:
    name: catalogue module architecture tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      test-project: ./Library.Modules.Catalogue.ArchTests